#!/bin/bash

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".c\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

printf "\nValidating C files:\n"

for FILE in $STAGED_FILES
do
  indent -kr -i8 "$FILE"

  if [[ "$?" == 0 ]]; then
    printf "\t\033[ Passed: $FILE\033[0m"
  else
    printf "\t\033[ Failed: $FILE\033[0m"
    PASS=false
  fi
done

printf "\nC validation completed!\n"

if ! $PASS; then
  printf "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass \n"
  exit 1
else
  printf "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
